### ISSUE TITLE
Uncaught exception: cannot load such file -- rails-assets-bootstrap-rtl

### ISSUE THREAD

**Issue by motro** [Yellowen/admin_lte-rails#1]
After installing and restarting the server I'm getting this error:
 
Error:[rake --prereqs] /Users/me/.rvm/gems/ruby-2.2.2/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- rails-assets-bootstrap-rtl (LoadError)

Any ideas?

**Comment by lxsameer** [comment]
You need to add the `rails-assets` source to your `Gemfile`, e.g:

```ruby
source 'http://rails-assets.org'
```

and bundle again. If error persist modify your `Gemfile` as follow:

```ruby 
source 'http://rails-assets.org' do
  gem 'rails-assets-bootstrap-rtl'
  gem 'rails-assets-jquery-knob'
  gem 'rails-assets-bootstrap-daterangepicker'
  gem 'rails-assets-jquery-sparkline'
  gem 'rails-assets-jquery-icheck'
end
```
I have to fix this bug, but let me know if this workaround works.

**Comment by motro** [comment]
Thanks for the quick response!

You have one line missing in the Gemfile: gem 'rails-assets-admin-lte'.
This is what I ended up adding:

```ruby
source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap-rtl'
  gem 'rails-assets-jquery-knob'
  gem 'rails-assets-bootstrap-daterangepicker'
  gem 'rails-assets-jquery-sparkline'
  gem 'rails-assets-jquery-icheck'
  gem 'rails-assets-admin-lte'
end 
```

Please consider adding this to the readme file.

**Comment by lxsameer** [comment]
Thanks for your feedback. I'll fix this bug and add the instructions to readme file.
