### ISSUE TITLE
Sidebar not open after click

### ISSUE THREAD

**Issue by rderoldan1** [Yellowen/admin_lte-rails#5]
When I have a sidebar with sub menu, After click in one option, I can't expand the menu again, I have to reload the page.

![screen shot 2015-11-25 at 1 36 13 a m](https://cloud.githubusercontent.com/assets/968973/11390133/efa95028-9314-11e5-8acf-db2037cfc176.png)
![screen shot 2015-11-25 at 1 35 52 a m](https://cloud.githubusercontent.com/assets/968973/11390134/efc491da-9314-11e5-9dab-5b7c137dd8bd.png)

**Comment by lxsameer** [comment]
Sorry I didn't understand you well, Do you have nested menu entries with more than two level ?

**Comment by rderoldan1** [comment]
I have a nested submenu, when the page load I can open it without problem,
but when I click one option and the page reload, I can't open again the sub
menu, I guess is related to turbolinks

On Wednesday, November 25, 2015, Sameer Rahmani <notifications@github.com>
wrote:

> Sorry I didn't understand you well, Do you have nested menu entries with
> more than two level ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yellowen/admin_lte-rails/issues/5#issuecomment-159513700>
> .
>


--

**Comment by lxsameer** [comment]
Hmmm I'm using it with turbolinks as well, Can you please take a look at javascript console for a possible warning or error. And it would be possible if you can send me a little gif or video that help me understand the problem better.

**Comment by rderoldan1** [comment]
Thanks for your time :smile: 

Here is a gif, as you can see, after clic on option, submenus never expand until full reload. I reviewed browser console and nothing is there.

![Image of Yaktocat](http://zippy.gfycat.com/InsignificantSnoopyArthropods.gif)

**Comment by lxsameer** [comment]
Thanks for the gif. If your using turbolinks make sure to exclude sidebar from replacing by turbolinks.

**Comment by rderoldan1** [comment]
@lxsameer Thanks :D I just add `data-no-turbolink` to the div. ;)

**Comment by rderoldan1** [comment]
The last workaround with `data-no-turbolink `, works if I click a button in the sidebar, but if I click other button in the page, it happens again, should I to disable turbo links at all, or do you have any suggestion?

**Comment by lxsameer** [comment]
use `data-turbolinks-permanent` to aside tag

**Comment by rderoldan1** [comment]
YEEES :+1:

**Comment by lxsameer** [comment]
Thanks ;)
